#!/bin/bash

# Script para facilitar a migração de questões dos arquivos originais para o formato Next.js
# Este script ajuda a copiar e converter questões do formato JavaScript original para TypeScript

echo "=== Script de Migração de Questões ==="
echo "Este script ajuda na migração das questões do formato original para Next.js"
echo ""

echo "Arquivos originais disponíveis:"
echo "1. _paginas/_administrator/_configuration_and_setup/_objectives1-2/questions.js"
echo "2. _paginas/_administrator/_configuration_and_setup/_objectives3-4/questions.js"
echo "3. _paginas/_administrator/_configuration_and_setup/_objectives5-6/questions.js"
echo "4. _paginas/_mcd/_official_training_test/_test_training_1/questions.js"
echo "5. _paginas/_mcd_2/_official_training_test/_test_training_1/questions.js"
echo "6. _paginas/_mcpa/_official_training_test/_test_training_1/questions.js"
echo ""

echo "Arquivos de destino (TypeScript):"
echo "1. src/data/administrator-objectives1-2.ts"
echo "2. src/data/administrator-objectives3-4.ts"
echo "3. src/data/administrator-objectives5-6.ts"
echo "4. src/data/mcd-level1.ts"
echo "5. src/data/mcd-level2.ts"
echo "6. src/data/mcpa-level1.ts"
echo ""

echo "Próximos passos para migrar questões:"
echo "1. Abra o arquivo original questions.js"
echo "2. Copie as questões do array questionsData"
echo "3. Converta para o formato TypeScript seguindo o exemplo:"
echo ""
echo "Formato original (JavaScript):"
echo "{"
echo "  \"question\": \"Pergunta aqui\","
echo "  \"type\": \"radio\","
echo "  \"options\": [\"A\", \"B\", \"C\", \"D\"],"
echo "  \"correctAnswer\": 0,"
echo "  \"justification\": \"<p>Justificativa...</p>\","
echo "  \"referenceLinks\": [\"https://exemplo.com\"],"
echo "  \"screenshots\": [\"imagem.png\"],"
echo "  \"videos\": []"
echo "}"
echo ""
echo "Formato novo (TypeScript):"
echo "{"
echo "  question: \"Pergunta aqui\","
echo "  type: \"radio\","
echo "  options: [\"A\", \"B\", \"C\", \"D\"],"
echo "  correctAnswer: 0,"
echo "  justification: \"Justificativa sem HTML\","
echo "  referenceLinks: [\"https://exemplo.com\"],"
echo "  screenshots: [\"/images/mcd/imagem.png\"],"
echo "  videos: []"
echo "}"
echo ""
echo "Observações importantes:"
echo "- Remover aspas das chaves dos objetos"
echo "- Limpar HTML das justificativas"
echo "- Ajustar caminhos das imagens para /images/[seção]/"
echo "- Manter a numeração das imagens correspondente"
